apiVersion: konvert.kumorilabs.io/v1alpha1
kind: Konvert
metadata:
  name: ingress-nginx
spec:
  chart: ingress-nginx
  kustomize: true
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
  path: upstream
  kustomize: true
