apiVersion: v1
data:
  orc-topology.cnf: |
    [client]
    user = {{ .Env.ORC_TOPOLOGY_USER }}
    password = {{ .Env.ORC_TOPOLOGY_PASSWORD }}
  orchestrator.conf.json: |-
    {
      "ApplyMySQLPromotionAfterMasterFailover": false,
      "BackendDB": "sqlite",
      "Debug": false,
      "DetachLostReplicasAfterMasterFailover": true,
      "DetectClusterAliasQuery": "SELECT CONCAT(SUBSTRING(@@hostname, 1, LENGTH(@@hostname) - 1 - LENGTH(SUBSTRING_INDEX(@@hostname,'-',-2))),'.',SUBSTRING_INDEX(@@report_host,'.',-1))",
      "DetectInstanceAliasQuery": "SELECT @@hostname",
      "DiscoverByShowSlaveHosts": false,
      "FailMasterPromotionIfSQLThreadNotUpToDate": true,
      "HTTPAdvertise": "http://{{ .Env.HOSTNAME }}-svc:80",
      "HostnameResolveMethod": "none",
      "InstancePollSeconds": 5,
      "ListenAddress": ":3000",
      "MasterFailoverDetachReplicaMasterHost": true,
      "MySQLHostnameResolveMethod": "@@report_host",
      "MySQLTopologyCredentialsConfigFile": "/etc/orchestrator/orc-topology.cnf",
      "OnFailureDetectionProcesses": [
        "/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcFailureDetection' 'Failure: {failureType}, failed host: {failedHost}, lost replcas: {lostReplicas}' || true",
        "/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true"
      ],
      "PostIntermediateMasterFailoverProcesses": [
        "/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostIntermediateMasterFailover' 'Failure type: {failureType}, failed hosts: {failedHost}, slaves: {countSlaves}' || true"
      ],
      "PostMasterFailoverProcesses": [
        "/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostMasterFailover' 'Failure type: {failureType}, new master: {successorHost}, slaves: {slaveHosts}' || true"
      ],
      "PostUnsuccessfulFailoverProcesses": [
        "/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcPostUnsuccessfulFailover' 'Failure: {failureType}, failed host: {failedHost} with {countSlaves} slaves' || true"
      ],
      "PreFailoverProcesses": [
        "/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true"
      ],
      "ProcessesShellCommand": "sh",
      "RaftAdvertise": "{{ .Env.HOSTNAME }}-svc",
      "RaftBind": "{{ .Env.HOSTNAME }}",
      "RaftDataDir": "/var/lib/orchestrator",
      "RaftEnabled": true,
      "RaftNodes": [],
      "RecoverIntermediateMasterClusterFilters": [
        ".*"
      ],
      "RecoverMasterClusterFilters": [
        ".*"
      ],
      "RecoveryIgnoreHostnameFilters": [],
      "RecoveryPeriodBlockSeconds": 300,
      "RemoveTextFromHostnameDisplay": ":3306",
      "SQLite3DataFile": "/var/lib/orchestrator/orc.db",
      "SlaveLagQuery": "SELECT TIMESTAMPDIFF(SECOND,ts,NOW()) as drift FROM sys_operator.heartbeat ORDER BY drift ASC LIMIT 1",
      "UnseenInstanceForgetHours": 1
    }
kind: ConfigMap
metadata:
  labels:
    app: mysql-operator
  name: mysql-operator-orc
