apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: rabbitmq-ha
  name: xray-rabbitmq-ha
  namespace: zero
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
