apiVersion: v1
kind: Service
metadata:
  labels:
    app: xray
    component: xray
  name: xray
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: router
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: xray
    component: xray
  type: ClusterIP
