apiVersion: v1
data:
  postgresql-password: ZG5qaDZxalZZYQ==
kind: Secret
metadata:
  labels:
    app: postgresql
    chart: postgresql-5.3.12
    heritage: Tiller
    release: postgresql
  name: postgresql
type: Opaque
