apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    chart: postgresql-5.3.12
    heritage: Tiller
    release: postgresql
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    release: postgresql
    role: master
  type: ClusterIP
