apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql-headless
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
  type: ClusterIP
