apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-operator
  name: mysql-operator
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: mysql-operator
  type: ClusterIP
