apiVersion: konvert.kumorilabs.io/v1alpha1
kind: Konvert
metadata:
  name: db01
spec:
  chart: mysql
  kustomize: true
  repo: https://charts.bitnami.com/bitnami
  version: 8.6.2
  values:
    auth:
      username: admin
      password: password
      rootPassword: password
