apiVersion: runtime.kumorilabs.io/v1alpha1
kind: Konvert
metadata:
  name: mysql
spec:
  # namespace: mysql
  chart: mysql
  kustomize: true
  # path: .
  # pattern: "%s-%s.yaml"
  repo: https://charts.bitnami.com/bitnami
  version: 8.6.2
