# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.6.2
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: konvert
  annotations:
    konvert.kumorilabs.io/generated-by: 'konvert'
    konvert.kumorilabs.io/chart: 'https://charts.bitnami.com/bitnami,mysql'
type: Opaque
data:
  mysql-root-password: "Q3R1T2hTazRYVg=="
  mysql-password: "RzBxcklxM0tQZQ=="
