# Source: mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  labels:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: konvert
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.6.2
  annotations:
    konvert.kumorilabs.io/chart: 'https://charts.bitnami.com/bitnami,mysql'
    konvert.kumorilabs.io/generated-by: 'konvert'
secrets:
  - name: mysql
