# Source: mysql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: konvert
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.6.2
  annotations:
    kumorilabs.io/generated-by: 'konvert'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql
