apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
namespace: cas
resources:
- clusterrole-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- clusterrolebinding-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- poddisruptionbudget-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- role-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- rolebinding-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- service-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
- serviceaccount-cluster-autoscaler-aws-cluster-autoscaler.yaml # konvert.kumorilabs.io/chart: https://kubernetes.github.io/autoscaler,cluster-autoscaler
