apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: xray
  name: xray
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xray
subjects:
- kind: ServiceAccount
  name: xray
