apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: rabbitmq-ha
  name: xray-rabbitmq-ha
  namespace: zero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xray-rabbitmq-ha
subjects:
- kind: ServiceAccount
  name: xray-rabbitmq-ha
  namespace: zero
