apiVersion: v1
kind: Secret
metadata:
  labels:
    app: xray
  name: xray-system-yaml
stringData:
  system.yaml: |
    configVersion: 1
    shared:
      logging:
        consoleLog:
          enabled: false
      jfrogUrl: "https://artifactory.cnative.io"
      database:
        type: "postgresql"
        driver: "org.postgresql.Driver"
        username: "xray"
        url: "postgres://xray-postgresql:5432/xraydb?sslmode=disable"
    server:
      mailServer: ""
      indexAllBuilds: ""
type: Opaque
